name: Build (Beta) 

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  build-android:
    if: contains(github.event.head_commit.message, '[build]')
    runs-on: ubuntu-latest
    outputs:
      arm64_link: ${{ steps.gdriveUpload_arm64.outputs.web-content-link }}
      armeabi_link: ${{ steps.gdriveUpload_armeabi.outputs.web-content-link }}
      x86_link: ${{ steps.gdriveUpload_x86.outputs.web-content-link }}
      universal_link: ${{ steps.gdriveUpload_universal.outputs.web-content-link }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Download keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo "$KEYSTORE_BASE64" | base64 --decode > android/app/anymex.jks
      - name: Set up signing variables
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
        run: |
          echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=anymex.jks" >> android/key.properties

      - name: Setup .env File
        env:
          AL_CLIENT_ID: ${{ secrets.AL_CLIENT_ID }}
          AL_CLIENT_SECRET: ${{ secrets.AL_CLIENT_SECRET }}
          SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
          SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}
          MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
          MAL_CLIENT_SECRET: ${{ secrets.MAL_CLIENT_SECRET }}
          CALLBACK_SCHEME: ${{ secrets.CALLBACK_SCHEME }}
        run: |
          echo "AL_CLIENT_ID=$AL_CLIENT_ID" > .env
          echo "AL_CLIENT_SECRET=$AL_CLIENT_SECRET" >> .env
          echo "SIMKL_CLIENT_ID=$SIMKL_CLIENT_ID" >> .env
          echo "SIMKL_CLIENT_SECRET=$SIMKL_CLIENT_SECRET" >> .env
          echo "MAL_CLIENT_ID=$MAL_CLIENT_ID" >> .env
          echo "MAL_CLIENT_SECRET=$MAL_CLIENT_SECRET" >> .env
          echo "CALLBACK_SCHEME=$CALLBACK_SCHEME" >> .env

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android with Split ABI
        run: flutter build apk --split-per-abi

      - name: Rename APKs
        run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/AnymeX-Android-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/AnymeX-Android-arm64.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/AnymeX-Android-x86_64.apk

      - name: Build Universal APK
        run: flutter build apk --release

      - name: Rename Universal APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/AnymeX-Android-universal.apk

          
      - name: Upload a Build Artifact
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: AnymeX-Android-arm64
          retention-days: 5
          compression-level: 9
          path: "build/app/outputs/flutter-apk/AnymeX-Android-arm64.apk"
      

      - name: Upload a Build Artifact
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: AnymeX-Android-armeabi-v7a
          retention-days: 5
          compression-level: 9
          path: "build/app/outputs/flutter-apk/AnymeX-Android-armeabi-v7a.apk"
      

      - name: Upload a Build Artifact
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: AnymeX-Android-x86_64
          retention-days: 5
          compression-level: 9
          path: "build/app/outputs/flutter-apk/AnymeX-Android-x86_64.apk"
        
          
      - name: Upload a Build Artifact
        if: ${{ env.SKIP_BUILD != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: AnymeX-Android-universal
          retention-days: 5
          compression-level: 9
          path: "build/app/outputs/flutter-apk/AnymeX-Android-universal.apk"
