name: changelog

on:
  workflow_run:
    workflows:
      - "Build and Release AnymeX"
    types:
      - completed
  workflow_dispatch:
    inputs:
      previous_tag:
        description: "Previous tag to compare against (optional, defaults to second most recent distinct tag)"
        required: false
      current_tag:
        description: "Current tag to generate changelog for (optional, defaults to latest tag)"
        required: false

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check Job Statuses
        id: check_jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          # For manual dispatch, always proceed
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger detected, skipping job checks"
            echo "all_jobs_success=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # For auto-trigger, fetch job details from the triggering workflow
          echo "Fetching jobs for workflow run ID: $RUN_ID"
          
          JOBS_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/jobs")
          
          echo "Jobs data retrieved"
          
          # Only check build-all-platforms jobs, ignore post-release jobs
          REQUIRED_JOBS=("build-all-platforms (android, ubuntu-latest)" "build-all-platforms (linux, ubuntu-latest)" "build-all-platforms (windows, windows-latest)" "build-all-platforms (macos, macos-latest)" "build-all-platforms (ios, macos-latest)")
          
          ALL_SUCCESS=true
          
          for REQUIRED_JOB in "${REQUIRED_JOBS[@]}"; do
            JOB_STATUS=$(echo "$JOBS_DATA" | jq -r --arg job "$REQUIRED_JOB" '.jobs[] | select(.name == $job) | .conclusion')
            
            if [ -z "$JOB_STATUS" ]; then
              echo "‚ö†Ô∏è Job '$REQUIRED_JOB' not found in workflow run"
              ALL_SUCCESS=false
              break
            elif [ "$JOB_STATUS" != "success" ]; then
              echo "‚ùå Job '$REQUIRED_JOB' failed with status: $JOB_STATUS"
              ALL_SUCCESS=false
              break
            else
              echo "‚úÖ Job '$REQUIRED_JOB' succeeded"
            fi
          done
          
          if [ "$ALL_SUCCESS" = true ]; then
            echo "‚úÖ All required build jobs succeeded"
          else
            echo "‚ùå Some required build jobs failed, skipping changelog generation"
          fi
          
          echo "all_jobs_success=$ALL_SUCCESS" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v4
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        with:
          fetch-depth: 0

      - name: Clear CHANGELOG.md
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: echo "" > CHANGELOG.md

      - name: Fetch Tags
        id: fetch_tags
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
          git fetch --tags
          TAGS=$(git tag --sort=-creatordate | tr '\n' ' ')
          echo "All tags: $TAGS"
          echo "tags=$TAGS" >> $GITHUB_ENV

      - name: Determine Tags for Comparison
        id: determine_tags
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
          if [ -n "${{ inputs.current_tag }}" ]; then
            CURRENT_TAG="${{ inputs.current_tag }}"
          else
            CURRENT_TAG=$(git describe --tags --abbrev=0)
          fi
          echo "Current tag: $CURRENT_TAG"
          echo "current_tag=$CURRENT_TAG" >> $GITHUB_ENV

          ALL_TAGS=(${{ env.tags }})
          PREV_TAG=""
          SECOND_PREV_TAG=""

          for TAG in "${ALL_TAGS[@]}"; do
            if [ "$TAG" != "$CURRENT_TAG" ]; then
              if [ -z "$PREV_TAG" ]; then
                PREV_TAG="$TAG"
              elif [ -z "$SECOND_PREV_TAG" ]; then
                SECOND_PREV_TAG="$TAG"
                break
              fi
            fi
          done

          if [ -n "${{ inputs.previous_tag }}" ]; then
            PREV_TAG="${{ inputs.previous_tag }}"
          elif [ "$PREV_TAG" == "$CURRENT_TAG" ] || [ -z "$PREV_TAG" ]; then
            PREV_TAG="$SECOND_PREV_TAG"
          fi

          if [ -z "$PREV_TAG" ]; then
            PREV_TAG=$(git rev-list --max-parents=0 HEAD)
          fi

          echo "Previous tag: $PREV_TAG"
          echo "prev_tag=$PREV_TAG" >> $GITHUB_ENV

      - name: Debug Commit Log
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: git log ${{ env.prev_tag }}..${{ env.current_tag }} --pretty=format:'%h %s'

      - name: Get Commit Messages Between Tags
        id: get_commits
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
          git log ${{ env.prev_tag }}..${{ env.current_tag }} --pretty=format:'%h|||%s' > commits.tmp
          echo "commits_file=commits.tmp" >> $GITHUB_OUTPUT

      - name: Categorize Commits
        id: categorize
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
          echo "Categorizing commits..."
          FEATURES=""; BUG_FIXES=""; REFACTORS=""; STYLE_CHANGES=""; PERFORMANCE=""; CHORES=""
          REPO_URL="https://github.com/${{ github.repository }}"

          while read -r HASH MESSAGE; do
            [ -z "$HASH" ] && continue
            CLEAN_MESSAGE=$(echo "$MESSAGE" | sed 's/#[0-9]\+//g' | sed 's/[^a-zA-Z0-9 .,:!-]//g' | tr '[:upper:]' '[:lower:]' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
            echo "Processing commit: $HASH - $CLEAN_MESSAGE"

            if [[ "$MESSAGE" =~ ^feat: ]]; then
              DESCR=$(echo "$CLEAN_MESSAGE" | sed 's/^feat://')
              FEATURES+="- [÷ç]($REPO_URL/commit/$HASH) $DESCR"$'\n'
            elif [[ "$MESSAGE" =~ ^fix:|^bug:|^improvement:|^patch: ]]; then
              DESCR=$(echo "$CLEAN_MESSAGE" | sed 's/^fix://; s/^bug://; s/^improvement://; s/^patch://')
              BUG_FIXES+="- [÷ç]($REPO_URL/commit/$HASH) $DESCR"$'\n'
            elif [[ "$MESSAGE" =~ ^refactor: ]]; then
              DESCR=$(echo "$CLEAN_MESSAGE" | sed 's/^refactor://')
              REFACTORS+="- [÷ç]($REPO_URL/commit/$HASH) $DESCR"$'\n'
            elif [[ "$MESSAGE" =~ ^style: ]]; then
              DESCR=$(echo "$CLEAN_MESSAGE" | sed 's/^style://')
              STYLE_CHANGES+="- [÷ç]($REPO_URL/commit/$HASH) $DESCR"$'\n'
            elif [[ "$MESSAGE" =~ ^perf: ]]; then
              DESCR=$(echo "$CLEAN_MESSAGE" | sed 's/^perf://')
              PERFORMANCE+="- [÷ç]($REPO_URL/commit/$HASH) $DESCR"$'\n'
            elif [[ "$MESSAGE" =~ ^chore:|^docs:|^build:|^ci: ]]; then
              DESCR=$(echo "$CLEAN_MESSAGE" | sed 's/^chore://; s/^docs://; s/^build://; s/^ci://')
              CHORES+="- [÷ç]($REPO_URL/commit/$HASH) $DESCR"$'\n'
            fi
          done < <(git log ${{ env.prev_tag }}..${{ env.current_tag }} --pretty=format:'%h %s')

          echo "### üÜï Changelog" > CHANGELOG.md
          [ -n "$FEATURES" ] && echo -e "### üåü Features\n$FEATURES\n" >> CHANGELOG.md
          [ -n "$BUG_FIXES" ] && echo -e "### üîß Bug Fixes & Improvements\n$BUG_FIXES\n" >> CHANGELOG.md
          [ -n "$REFACTORS" ] && echo -e "### üîß Refactors\n$REFACTORS\n" >> CHANGELOG.md
          [ -n "$STYLE_CHANGES" ] && echo -e "### üé® Style Changes\n$STYLE_CHANGES\n" >> CHANGELOG.md
          [ -n "$PERFORMANCE" ] && echo -e "### üöÄ Performance Improvements\n$PERFORMANCE\n" >> CHANGELOG.md
          [ -n "$CHORES" ] && echo -e "### üßπ Chores & Documentation\n$CHORES\n" >> CHANGELOG.md

          CURRENT_TAG_SAFE=$(echo "${{ env.current_tag }}" | sed 's/[^a-zA-Z0-9.-]//g')
          echo "![Total Downloads](https://img.shields.io/github/downloads/RyanYuuki/AnymeX/total?style=for-the-badge&label=TOTAL%20DOWNLOADS&labelColor=black&color=white) ![Current Release](https://img.shields.io/github/downloads/RyanYuuki/AnymeX/${CURRENT_TAG_SAFE}/total?style=for-the-badge&label=CURRENT%20RELEASE&labelColor=black&color=white)" >> CHANGELOG.md
          rm -f commits.tmp
        shell: /usr/bin/bash -e {0}

      - name: Debug CHANGELOG.md
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: cat CHANGELOG.md

      - name: Commit and Push Changelog
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
          git config --global user.name "Git Paneer"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit --allow-empty -m "Update changelog for version ${{ env.current_tag }}"
          git push origin HEAD:main

      - name: Generate Plaintext Changelog for F-Droid/Izzy
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
         mkdir -p fastlane/metadata/android/en-US/changelogs
         awk '/^### üÜï Changelog/{flag=1; next}/^![Tt]otal/{flag=0}flag' CHANGELOG.md \
         | sed -E 's/!\[[^]]*\]\([^)]*\)//g' \
         | sed -E 's/\[[^]]*\]\([^)]*\)//g' \
         | sed 's/^÷ç[[:space:]]*/- /' \
         | sed '/^$/N;/^\n$/D' \
         > fastlane/metadata/android/en-US/changelogs/default.txt

      - name: Debug default.txt
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: cat fastlane/metadata/android/en-US/changelogs/default.txt

      - name: Commit and Push default.txt
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        run: |
          git config --global user.name "Git Paneer"
          git config --global user.email "actions@github.com"
          git add fastlane/metadata/android/en-US/changelogs/default.txt
          git commit --allow-empty -m "Update default.txt for version ${{ env.current_tag }}"
          git push origin HEAD:main

      - name: Create or Update Release
        if: ${{ steps.check_jobs.outputs.all_jobs_success == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: CHANGELOG.md
          tag: ${{ env.current_tag }}
          allowUpdates: true
