name: Build (Beta) idk

on:
  push:
    branches:
      - idk
  workflow_dispatch:

jobs:
  sendMessage:
    runs-on: ubuntu-latest
    #needs: [build-android, build-ios, build-linux, build-windows, build-macos]
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download last SHA artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: idk.yml
          name: last-sha
        continue-on-error: true

      - name: Get Commits Since Last Run
        run: |
          # Determine last commit SHA
          if [ -f last_sha.txt ]; then
              LAST_SHA=$(cat last_sha.txt)
          else
              LAST_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          
          echo "Commits since $LAST_SHA:"
          
          # Store commit logs with short hashes
          COMMIT_LOG=$(git log $LAST_SHA..HEAD --pretty=format:"* [%h](https://github.com/${{ github.repository }}/commit/%H) : %s")
          
          # Save commit logs to a file
          echo "$COMMIT_LOG" > commit_log.txt
          
          cat commit_log.txt
          COMMIT_LOG=$(cat commit_log.txt) 
          echo "COMMIT_LOG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          # Extract branch name from github.ref
          BRANCH=${{ github.ref }}
          BRANCH=${BRANCH#refs/heads/}
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}
        env:
          CI: true
        continue-on-error: true

      - name: Save Current SHA for Next Run
        run: echo ${{ github.sha }} > last_sha.txt

      - name: Categorize Commits (Limit to 5 Each)
        run: |
          #!/bin/bash
          
          # Read commit log
          COMMIT_LOG=$(cat commit_log.txt)
          
          # Function to get up to 5 commits per category
          get_limited_commits() {
            echo "$1" | grep -E "$2" | head -n 5 2>/dev/null || echo ""
          }

          # Categorize commits (limit to 5 per category)
          FEATURES=$(get_limited_commits "$COMMIT_LOG" "feat")
          FIXES=$(get_limited_commits "$COMMIT_LOG" "(fix|bug|improvement|patch)")
          REFACTORS=$(get_limited_commits "$COMMIT_LOG" "refactor")
          STYLE=$(get_limited_commits "$COMMIT_LOG" "style")
          PERFORMANCE=$(get_limited_commits "$COMMIT_LOG" "perf")
          CHORES=$(get_limited_commits "$COMMIT_LOG" "(chore|docs|build|ci)")
          
          MESSAGE="### 📝 Commit Summary"
          
          if [ -n "$FEATURES" ]; then
            MESSAGE+="\n\n**🚀 Features:** $FEATURES"
          fi
          if [ -n "$FIXES" ]; then
            MESSAGE+="\n\n**🐛 Fixes:** $FIXES"
          fi
          if [ -n "$REFACTORS" ]; then
            MESSAGE+="\n\n**🔧 Refactors:** $REFACTORS"
          fi
          if [ -n "$STYLE" ]; then
            MESSAGE+="\n\n**💅 Style:** $STYLE"
          fi
          if [ -n "$PERFORMANCE" ]; then
            MESSAGE+="\n\n**⚡ Performance:** $PERFORMANCE"
          fi
          if [ -n "$CHORES" ]; then
            MESSAGE+="\n\n**🛠 Chores:** $CHORES"
          fi
          
          # Save to environment variable properly
          {
            echo "COMMIT_MESSAGE<<EOF"
            echo -e "$MESSAGE"
            echo "EOF"
          } >> "$GITHUB_ENV" || { echo "Failed to write to GITHUB_ENV"; exit 1; }
          
          # Use MESSAGE in formatted_notes.txt safely
          echo -e "$MESSAGE" > formatted_notes.txt || { echo "Failed to write formatted_notes.txt"; exit 1; }


      - name: Display Commit Message
        run: |
          echo "$MESSAGE"
        shell: /usr/bin/bash -e {0}

      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_ALPHA }}
        run: |
  
          # Define default color
          default_color="#1ac4c5"
          
          # Convert HEX to Decimal
          hex_to_decimal() { printf '%d' "0x${1#"#"}"; }
          embed_color=$(hex_to_decimal "$default_color")
                    
          # Construct Discord payload
          discord_data=$(jq -nc \
            --arg field_value "$MESSAGE" \
            --arg footer_text "Version beta" \
            --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)" \
            --argjson embed_color "$embed_color" \
            '{
              "content": "<@&1313089691523878942>",
              "embeds": [
                {
                  "title": "🚀 New Beta Release",
                  "color": $embed_color,
                  "fields": [
                    {
                      "name": "Commits:",
                      "value": $field_value,
                      "inline": false
                    }
                  ],
                  "footer": {
                    "text": $footer_text
                  },
                  "timestamp": $timestamp
                }
              ]
            }')
          
          # Debugging: Print the payload
          echo "Debug: Discord Payload -> $discord_data"
          
          # Validate JSON before sending
          echo "$discord_data" | jq . || { echo "Invalid JSON"; exit 1; }
          
          # Send the message to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$discord_data" \
               "$DISCORD_WEBHOOK_URL"

      - name: Upload Current SHA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-sha
          path: last_sha.txt

      - name: Send Discord Notification with Download Links
        env:
          ANDROID_ARM64_LINK: ${{ needs.build-android.outputs.arm64_link }}
          ANDROID_ARMEABI_LINK: ${{ needs.build-android.outputs.armeabi_link }}
          ANDROID_X86_LINK: ${{ needs.build-android.outputs.x86_link }}
          ANDROID_UNIVERSAL_LINK: ${{ needs.build-android.outputs.universal_link }}
          IOS_LINK: ${{ needs.build-ios.outputs.ios_link }}
          LINUX_ZIP_LINK: ${{ needs.build-linux.outputs.linux_zip_link }}
          LINUX_APPIMAGE_LINK: ${{ needs.build-linux.outputs.linux_appimage_link }}
          LINUX_RPM_LINK: ${{ needs.build-linux.outputs.linux_rpm_link }}
          WINDOWS_ZIP_LINK: ${{ needs.build-windows.outputs.windows_zip_link }}
          WINDOWS_EXE_LINK: ${{ needs.build-windows.outputs.windows_exe_link }}
          MACOS_LINK: ${{ needs.build-macos.outputs.macos_link }}
        run: |
          MESSAGE="Beta Released
      
          🔹 [Download]($ANDROID_ARM64_LINK) | **Android (arm64)**
          🔹 [Download]($ANDROID_ARMEABI_LINK) | **Android (armeabi-v7a)**
          🔹 [Download]($ANDROID_UNIVERSAL_LINK) | **Android (universal)**
          🔹 [Download]($ANDROID_X86_LINK) | **Android (x86 & x64)**
          🔹 [Download]($WINDOWS_ZIP_LINK) | **Windows ZIP**
          🔹 [Download]($WINDOWS_EXE_LINK) | **Windows EXE**
          🔹 [Download]($LINUX_ZIP_LINK) | **Linux ZIP**
          🔹 [Download]($LINUX_APPIMAGE_LINK) | **Linux AppImage**
          🔹 [Download]($LINUX_RPM_LINK) | **Linux RPM**
          🔹 [Download]($IOS_LINK) | **iOS**
          🔹 [Download]($MACOS_LINK) | **macOS**"

          # Send to Discord if the message is not empty
          if [[ -n "$MESSAGE" ]]; then
            curl -H "Content-Type: application/json" \
                 -d "{\"content\": \"$MESSAGE\"}" \
                 "${{ secrets.DISCORD_WEBHOOK_ALPHA }}"
          fi

      - name: Send Telegram Notification
        env:
          ANDROID_ARM64_LINK: ${{ needs.build-android.outputs.arm64_link }}
          ANDROID_ARMEABI_LINK: ${{ needs.build-android.outputs.armeabi_link }}
          ANDROID_X86_LINK: ${{ needs.build-android.outputs.x86_link }}
          ANDROID_UNIVERSAL_LINK: ${{ needs.build-android.outputs.universal_link }}
          IOS_LINK: ${{ needs.build-ios.outputs.ios_link }}
          LINUX_ZIP_LINK: ${{ needs.build-linux.outputs.linux_zip_link }}
          LINUX_APPIMAGE_LINK: ${{ needs.build-linux.outputs.linux_appimage_link }}
          LINUX_RPM_LINK: ${{ needs.build-linux.outputs.linux_rpm_link }}
          WINDOWS_ZIP_LINK: ${{ needs.build-windows.outputs.windows_zip_link }}
          WINDOWS_EXE_LINK: ${{ needs.build-windows.outputs.windows_exe_link }}
          MACOS_LINK: ${{ needs.build-macos.outputs.macos_link }}
        run: |
          TELEGRAM_MESSAGE="🎉 *Beta Released* 🎉
      
          🔹 [Download]($ANDROID_ARM64_LINK) | **Android (arm64)**
          🔹 [Download]($ANDROID_ARMEABI_LINK) | **Android (armeabi-v7a)**
          🔹 [Download]($ANDROID_UNIVERSAL_LINK) | **Android (universal)**
          🔹 [Download]($ANDROID_X86_LINK) | **Android (x86 & x64)**
          🔹 [Download]($WINDOWS_ZIP_LINK) | **Windows ZIP**
          🔹 [Download]($WINDOWS_EXE_LINK) | **Windows EXE**
          🔹 [Download]($LINUX_ZIP_LINK) | **Linux ZIP**
          🔹 [Download]($LINUX_APPIMAGE_LINK) | **Linux AppImage**
          🔹 [Download]($LINUX_RPM_LINK) | **Linux RPM**
          🔹 [Download]($IOS_LINK) | **iOS**
          🔹 [Download]($MACOS_LINK) | **macOS**"

          curl -sS -f -X POST \
              "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
              -F "message_thread_id=${{ secrets.TELEGRAM_THREAD_ID }}" \
              -F parse_mode="Markdown" \
              -F disable_notification=true \
              -F "text=$TELEGRAM_MESSAGE"
              
