name: Send Commit Summary and Release Assets

on:
  push:
    branches:
      - idk  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Commits Since Last Run
        id: get_commits
        run: |
          if [ -f last_sha.txt ]; then
            LAST_SHA=$(cat last_sha.txt)
            echo "‚úÖ Found last SHA: $LAST_SHA"
          else
            echo "‚ö†Ô∏è No previous SHA found, using first commit."
            LAST_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          
          echo "Fetching commits since $LAST_SHA..."
          COMMIT_LOGS=$(git log $LAST_SHA..HEAD --pretty=format:"‚óè %s ~%an [÷ç](https://github.com/${{ github.repository }}/commit/%H)")
          
          if [ -z "$COMMIT_LOGS" ]; then
            echo "‚ö†Ô∏è No new commits found."
            exit 0
          fi

          echo "$COMMIT_LOGS" > commit_log.txt
          echo "$COMMIT_LOGS" | tee commit_log.txt

          echo "HEAD" > last_sha.txt

      - name: Categorize Commits
        run: |
          #Start with release header
          echo "**üöÄ New Release: Beta**" > header.txt
          echo "**üöÄ Features**" > TFeatures.txt
          echo "**üêõ Fixes**" > TFixes.txt
          echo "**üîß Refactors**" > TRefactors.txt
          echo "**üíÖ Style**" > TStyle.txt
          echo "**üõ† Chores**" > TChores.txt

          # Read from COMMIT_LOGS variable
          while IFS= read -r line; do
              if [[ $line == feat* ]]; then
                  echo "$line" >> TFeatures.txt
              elif [[ $line =~ ^(fix|bug|improvement|patch) ]]; then
                  echo "$line" >> TFixes.txt
              elif [[ $line == refactor* ]]; then
                  echo "$line" >> TRefactors.txt
              elif [[ $line == style* ]]; then
                  echo "$line" >> TStyle.txt
              elif [[ $line =~ ^(chore|docs|build|ci) ]]; then
                  echo "$line" >> TChores.txt
              fi
          done <<< "$COMMIT_LOGS"  # Use the variable directly

          # Process each file through the parser
          chmod +x scripts/tel_commit_parser.sed

          ./scripts/tel_commit_parser.sed TFeatures.txt > TFeaturesT.txt
          ./scripts/tel_commit_parser.sed TFixes.txt > TFixesT.txt
          ./scripts/tel_commit_parser.sed TRefactors.txt > TRefactorsT.txt
          ./scripts/tel_commit_parser.sed TStyle.txt > TStyleT.txt
          ./scripts/tel_commit_parser.sed TChores.txt > TChoresT.txt

          # Check and remove empty categories
          if [ ! -s TFeaturesT.txt ]; then rm -f TFeaturesT.txt; fi
          if [ ! -s TFixesT.txt ]; then rm -f TFixesT.txt; fi
          if [ ! -s TRefactorsT.txt ]; then rm -f TRefactorsT.txt; fi
          if [ ! -s TStyleT.txt ]; then rm -f TStyleT.txt; fi
          if [ ! -s TChoresT.txt ]; then rm -f TChoresT.txt; fi

          # Combine categories into final output
          {
              cat header.txt
              echo ""
              [ -f TFeaturesT.txt ] && echo -n "$(cat TFeaturesT.txt) <blockquote>$(cat TFeatures.txt)</blockquote> "
              [ -f TFixesT.txt ] && echo -n "$(cat TFixesT.txt) <blockquote>$(cat TFixes.txt)</blockquote> "
              [ -f TRefactorsT.txt ] && echo -n "$(cat TRefactorsT.txt) <blockquote>$(cat TRefactors.txt)</blockquote> "
              [ -f TStyleT.txt ] && echo -n "$(cat TStyleT.txt) <blockquote>$(cat TStyle.txt)</blockquote> "
              [ -f TChoresT.txt ] && echo -n "$(cat TChoresT.txt) <blockquote>$(cat TChores.txt)</blockquote> "
              echo ""
              echo "‚ùì<a href='https://github.com/${{ github.repository }}/blob/main/INSTALLATION.md'>Don't know which version to download? Click here!</a>"
              echo ""
              echo "üìå <a href='https://github.com/${{ github.repository }}/releases/tag/${{ env.LATEST_TAG }}'>Full changelog</a>"
          } > output.txt

          if [ ! -s output.txt ]; then
              echo "No commits found. Skipping Telegram message."
              exit 0
          fi

          markdown_info_tel=$(< output.txt)
          echo "Final Telegram Message:"
          echo "$markdown_info_tel"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
              -d "chat_id=$TELEGRAM_CHAT_ID" \
              -d "text=$markdown_info_tel" \
              -d "parse_mode=HTML" \
              -d "disable_web_page_preview=true"
