name: Send Telegram Release Notes

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  send_telegram_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Changelog Entry
        id: changelog
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          MESSAGE="<b>🚀 New Release: ${VERSION}</b>\n\n"
          MESSAGE+="$(awk '/^## /{f=!f} f' CHANGELOG.md | sed -n '2,/^## /{s/^🔹 /🔗 /; p}' | sed 's/[^]]*(https:\/\/github.com\/RyanYuuki\/AnymeX\/commit\/[^)]*)/<a href=\"https:\/\/github.com\/RyanYuuki\/AnymeX\/commit\/\2\">\1<\/a>:/g')"
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Send Message to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{
            "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
            "text": "'"${{ env.MESSAGE }}"'",
            "parse_mode": "HTML"
          }'